use jetcrab::api::debug::DebugEngine;
use jetcrab::api::Engine;

fn main() {
    println!("=== Debug For Loop Bytecode ===");

    let mut debug_engine = DebugEngine::new();

    println!("\n1. Testing for loop bytecode generation:");

    let code = "for (let i = 0; i < 3; i++) { let sum = 0; sum += i; }";

    println!("\nCode: {}", code);

    println!("\n=== Generated Bytecode ===");
    let bytecode = debug_engine.generate_bytecode(code);
    match bytecode {
        Ok(instructions) => {
            for (i, instruction) in instructions.iter().enumerate() {
                println!("  {}: {:?}", i, instruction);
            }
        }
        Err(e) => println!("Error generating bytecode: {:?}", e),
    }

    println!("\n=== AST Generation ===");
    let ast = debug_engine.generate_ast(code);
    match ast {
        Ok(node) => {
            println!("AST: {:#?}", node);
        }
        Err(e) => println!("Error generating AST: {:?}", e),
    }
}
